### PR TITLE
Add Ctrl+Shift+arrow navigation for selecting next/previous highlighted reference

### PR DESCRIPTION
**Pull request by rik-smeets**

### CODE REVIEW

**Comment by rik-smeets** [comment]
@rebornix I was hoping you could take a look at this PR? Thank you very much.

**Comment by auchenberg** [comment]
@rik-smeets Can you point me to the original mappings in VS? We want to make sure there's reference why this shortcut is added.

**Comment by rik-smeets** [comment]
@auchenberg I'm not sure where to find the original mappings on a Microsoft website, but over at http://visualstudioshortcuts.com/2017/ you can find it under _Next Highlighted Reference_ and _Previous Highlighted Reference_ reference.

**Comment by auchenberg** [comment]
LGTM. Thanks @rik-smeets !

**Pull request merged**
